name: bog
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  feather_icons: ^1.2.0
  dio: ^4.0.4
  get_storage: ^2.0.3
  image_picker: ^0.8.5
  flutter_iconly: ^1.0.2
  carousel_slider: ^4.0.0
  flutter_rating_bar: ^4.0.0
  
  cached_network_image: ^3.2.0
  flutter_svg: ^1.0.3
  flutter_native_splash: ^2.1.3+1
  pull_to_refresh: ^2.0.0
  loading_animation_widget: ^1.1.0+5
  shimmer: ^2.0.0
  flutter_custom_tabs: ^1.0.4
  http: ^0.13.4
  equatable: ^2.0.3
  date_time_format: ^2.0.1
  dropdown_search: ^5.0.3
  loading_indicator: ^3.0.2
  qr_flutter: ^4.0.0
  image: ^3.1.0
  flutter_feather_icons: ^2.0.0+1
  qr_code_scanner: ^1.0.0
  flutter_barcode_scanner: ^2.0.0
  path_provider: ^2.0.14
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  toggle_switch: ^2.0.1
  nigerian_states_and_lga: ^1.0.0
  country_picker: ^2.0.16
  dart_countries: ^3.0.2
  otp_text_field: ^1.1.3
  animated_toggle_switch: ^0.5.2
  vertical_tabs_flutter: ^1.0.0
  file_picker: ^5.2.2
  d_chart: ^0.1.0
  syncfusion_flutter_charts: ^20.3.61
  fl_chart: ^0.55.2
  url_launcher: ^6.1.10
  expandable: ^5.0.1
  badges: ^3.0.2
  flutter_paystack: ^1.0.7
  json_to_form: ^0.0.5
  intl: ^0.17.0

  flutter_file_downloader: ^1.1.0+1
 
  flutter_pdfview: ^1.2.9
  form_field_validator: ^1.1.0
  photo_view: ^0.14.0
  path: ^1.8.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/bog_new_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FF3F79AD"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: PP Telegraf
      fonts:
        - asset: assets/images/pptelegraf-regular.otf